services:
  frontend:
    build:
      context: frontend
    command: npm run dev -- --host
    ports:
      - 3000:5173
    networks:
      - relay_default
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  backend:
    build:
      context: backend
    command: npm start
    ports:
      - 8000:8000
    networks:
      - relay_default
    depends_on:
      - mysql
      - redis
    restart: on-failure
    volumes:
      - ./backend:/app
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    networks:
      - relay_default
    restart: always
    volumes:
      - mysqldata:/var/lib/mysql
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    networks:
      - relay_default
    restart: always
    volumes:
      - redisdata:/data
networks:
  relay_default:
    driver: bridge
volumes:
  mysqldata:
  redisdata:
