name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' 

    - name: Install dependencies
      run: cd backend |
            npm ci
            
    - name: Create .env file
      run: |
        echo "NODE_ENV=test" > .env
        echo "DATABASE_URL=file:./test.db" >> .env


    - name: Run run test
      run: npm run test
